export default {
    EMP_LOGIN_TITLE: 'Employee',
    DRIVER_LOGIN_TITLE: 'Driver',
    ADMIN_LOGIN_TITLE: 'Admin',
    DRIVER_REG_TITLE: 'Register',
    REG_BTN_TITLE: 'Register',
    BOOK_BTN_TITLE: 'Book Cab',
    OKTA_LOGIN: 'Login with Okta',
    REVOKE_BTN_TITLE: 'Revoke',
    VEHICLEINPUT: 'PHONE/VEHICLE',
    DRIVER_LOGIN: 'SignIn using OTP',
    DRIVER_LOGIN_AFTER_OTP: 'SignIn',
    DRIVER_NAME: 'DRIVER FIRST NAME',
    DRIVER_PHONE: 'PHONE NUMBER',
    DRIVER_VEHICLE: 'VEHICLE NUMBER',
    DRIVER_LICENSE: 'DRIVING LICENSE',
    DRIVER_ADDRESS: 'HOME ADDRESS',
    ENTER_OTP: 'Enter OTP',
    CANCEL_PICK: 'Cancel Pickup',
    CANCEL_DROP: 'Cancel Drop',
    DESC_TITLE: 'Enter Time Change Request',
    SUBMIT_REQUEST: 'Submit Request',
    CANCEL_REQUEST: 'Cancel',
    CANCEL_TRIP: 'Cancel Trip',
    UPDATE_TRIP: 'Update Trip',
    UPDATE_DROP: 'Update Drop',
    UPDATE_PICK: 'Update Pickup',
    LOGOUT: 'Signout',
    LOGIN_BTN_ADMIN: 'Login',
    LOGOUT_BTN_ADMIN: 'Logout',
    DRIVER_LIST_ADMIN: 'Driver List',
    EMPLOYEE_LIST_ADMIN: 'Employee List',
    ASSIGN_TRIP: 'Assign',
    BOOKED: 'Booked',
    REMOVE_DRIVER: 'Remove Driver',
    SEARCH_EMP: 'Go',
    EMP_BTN: 'Employee',
    UPDATE_TIME: 'Update Time',
    SIGNUP_BTN: 'Signup',
    SUB_LINE: 'Enter Subject',
    UPDATE: 'Update',
    CANCELSTATUS: 'CANCELLED',
    DRIVER_START_TRIP: 'START TRIP',
    DRIVER_END_TRIP: 'END TRIP',
    SUBMIT: 'Submit'
}